config/routes.rb
MxitGame::Application.routes.draw do
  resources :users, :only => [:index] do
    resource :profile, :only => [:index, :new, :create, :show]
    resource :plot, :only => [:new, :create, :show]

    namespace :messaging do
      resources :message, :only => [:new, :create]
    end
  end
  get '/profile', to: 'profiles#show' # current user's profile

  namespace :messaging do
    # Conversations are created when new messages are sent
    resources :conversation, :only => [:index, :show]
    match 'inbox', to: 'conversation#index'
  end

  # Game actions:
  get '/game/build', to: 'game#build'
  get '/game/destroy', to: 'game#destroy'
  get '/game/upgrade', to: 'game#upgrade'

  #get '/temp/second' => 'temp#second'
  root to: 'home#index'
  #root :to => 'temp#first'
end

app/models/profile.rb
class Profile
  include Mongoid::Document
  # Stores the name of the player
  field :name,          type: String

  # Player name validation (Make sure it is unique and correct length)
  validates_uniqueness_of   :name, :case_sensitive => false
  validates_length_of       :name, minimum: 2, maximum: 20

  # The parent document (what the profile belongs to)
  embedded_in :user

  # Indexes (database optimization)
  index({ name: 1 }, { unique: true, name: "profile_name_index" })
end

app/controllers/profiles_controller.rb
# Controller involved with profile creation and maintenance

class ProfilesController < GameController
  skip_before_filter :set_username, :only => [:new, :create]
  skip_before_filter :set_plotname, :only => [:new, :create]

  def index
  end

  def show
    if params[:destroy]
      @user.profile.delete
      render 'destroy' and return
    end
    params[:user_id] ||= @user.id
    @profile = User.find(params[:user_id]).profile
    # Update the other player
    @profile.user.update! if @profile.user != @user
    redirect_to root_path unless @profile
  end

  def new
    @profile = Profile.new()
  end

  def create
    @profile = @user.build_profile(params[:profile])
    render :new unless @user.profile.save
  end
end

app/views/profiles/create.html.erb
<%= render "mxit/debug_header" %>
User profile created

app/views/profiles/destroy.html.erb
<%= render "mxit/debug_header" %>
Profile deleted.

app/views/profiles/index.html.erb
<%= render "mxit/debug_header" %>
<% @profile_users.each do |user| %>
  <%= link_to user.profile.name, user_profile_path(user) %> <br>
<% end %>

app/views/profiles/new.html.erb
<%= render "mxit/debug_header" %>
<% @profile.errors.full_messages.each do |msg| %>
  <b> :( <%= msg %></b><br/>
<% end %>
<%= form_for [@user, @profile], :url => user_profile_path(@user) do |f| %>
  <%= f.label :name, 'Choose your name: ' %> <br/>
  <%= f.text_field :name %> <br/>
  <%= f.submit 'Send' %>
<% end %>

app/views/profiles/show.html.erb
<%= render "mxit/debug_header" %>
<b> <%= @profile.name %>: </b> <%= link_to "Refresh", user_profile_path(@profile.user) %><br>
<%= link_to_if((@user != @profile.user), "Send Message", new_user_messaging_message_path(@profile.user)){} %><br>
<b>Build: </b> <br>
<%= link_to "Build Plasma Generator", game_build_path(:resource_type => :plasma, :object_type => :generator) %> <br>
<b>Resource Generators: </b><br>
<% @profile.user.plot.resource_generators.each do |gen| %>
  <b> <%= gen.resource_type %>: </b> <%= gen.level %> |
  <%= upgrade_link(gen) %> |
  <%= link_to "Destroy", game_destroy_path(id: gen.id) %> <br>
<% end %>
<b>Resource Storage: </b><br>
<% @profile.user.plot.silos.each do |silo| %>
  <b> <%= silo.resource_type %>: </b> <%= silo.level %> <br>
<% end %>