config/routes.rb
MxitGame::Application.routes.draw do
  resources :users, :only => [:index] do
    resource :profile, :only => [:index, :new, :create, :show]
    resource :plot, :only => [:new, :create, :show]

    namespace :messaging do
      resources :message, :only => [:new, :create]
    end
  end
  get '/profile', to: 'profiles#show' # current user's profile

  namespace :messaging do
    # Conversations are created when new messages are sent
    resources :conversation, :only => [:index, :show]
    match 'inbox', to: 'conversation#index'
  end

  # Game actions:
  get '/game/build', to: 'game#build'
  get '/game/destroy', to: 'game#destroy'
  get '/game/upgrade', to: 'game#upgrade'

  #get '/temp/second' => 'temp#second'
  root to: 'home#index'
  #root :to => 'temp#first'
end

app/controllers/temp_controller.rb
class TempController < MxitController
  def first
  end

  def second
  end

  def third
  end

  def fourth
  end
end

app/views/temp/first.html.erb
<%= render 'debug_header' %>
<body bgcolor = "black">
<start title>
<b><h1><font color ="blue">Welcome to The Future!</font></h1></b>
</end title>
<p>
<img src = "/thefuture.jpg">
<P>
<font color="white">The Future is a free-to-play game where you compete against everyone else playing, to see who can become the Ultimate Future Legend with the strongest Planet Plots.
</font><p>
<font color="gray">---</font
<p>
<font color ="white">Its the year 3000
<p>
<font color ="white">Humans have discovered other life forms in the Galaxy from other solar systems which changes the way humans have lived .
<p>
<font color ="white">Invasions from aliens and other life forms came and destroyed Earth.
<br/>
<font color ="white">Humans then took everything they had and moved to a new planet called Ferric. It's one of the biggest planets in our solar system.
<p>
<font color ="red">Its up to you, Watch out!
<br/>
<font color ="red">Its Kill or be Killed!
<p>
<font color ="gray">*OBJECTIVE 1: <font color ="orange">Grow your Planet Plots and become the Ultimate Future Legend!
<br/>
<font color ="gray">*OBJECTIVE 2:  <font color ="orange">Defend yourself against other humans and life forms, then strike back!
<p>
 <font color ="red">YOU ARE NOW ENTERING THE FUTURE!
<p>
<b><h2><font color ="grey"><%= link_to "Next", new_user_profile_path(@user) %></h2></b>
</p>